site_name: gpyrn
repo_url: https://github.com/iastro-pt/gpyrn/
edit_uri: ""

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


nav:
  - Welcome: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 'getting_started.md'
  - Examples:
    - examples/index.md
    - One dataset: 'examples/one_dataset.md'
    - Several datasets: 'examples/several_datasets.md'
  - 'benchmarks.md'
  - Reference:
    - meanfunc: 'reference/meanfunc.md'
    - covfunc: 'reference/covfunc.md'
  - 'Issue Tracker': 'https://github.com/iastro-pt/gpyrn/issues'

copyright: Copyright &copy; 2021 - 2022 Institute of Astrophysics and Space Sciences
# extra:
#   generator: false

plugins:
  - search
  - mkdocstrings
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            members_order: source
            show_source: false
      watch:
        - gpyrn
      custom_templates: templates


markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic:
      mode: view
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons



extra_javascript:
  - /docs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# extra:
#   version:
#     provider: mike