name: Docs

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Install"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: pip install jupyter

      - name: Run examples
        run: |
          make -C docs

      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
