name: Docs

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Install"]
    types:
      - completed

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - name: Run examples
        run: |
          make -C docs

      - name: Install doc dependencies
        run: |
          pip install mkdocs mkdocstrings mkdocs-material

      - name: Build docs
        run: |
          mkdocs build

      # - name: Publish docs
      #   run: |
      #     mkdocs gh-deploy --force